name: Auto PR
on:
  pull_request:
    types: [opened]
jobs:
  autoComment:
    runs-on: ubuntu-latest
    name: A auto-comment to a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Thanks for opening this pull request! Please check out the contributing guidelines in README.md.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@v1