name: Auto project

on:
  check_suite:
    types: [completed]
jobs:
  auto-project:
    defaults:
      run:
        shell: bash
        working-directory: scripts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Python 版本的语义版本范围矩阵或准确的版本
        python-version: '3.x' 
        # 可选 - x64 或 x86 架构，默认为 x64
        architecture: 'x64' 
    # 您可以打印当前 Python 版本以测试矩阵
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: Add to project
      env: 
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: python auto_project.py "$ACCESS_TOKEN"
